# Generated by Django 6.0 on 2026-01-03 18:42

import django.core.validators
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gallery.models.gallery_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), gallery.models.validate_image_size], verbose_name='Imagen')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('caption', models.TextField(blank=True, verbose_name='Descripción/Caption')),
                ('alt_text', models.CharField(help_text='Descripción de la imagen para accesibilidad y SEO', max_length=200, verbose_name='Texto alternativo (ALT)')),
                ('category', models.CharField(choices=[('vestuarios', 'Vestuarios'), ('cardio', 'Cardio'), ('elgym', 'El Gym'), ('musculacion', 'Musculación')], max_length=50, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Número menor aparece primero', verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Foto de Galería',
                'verbose_name_plural': 'Fotos de Galería',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
