# Generated by Django 4.2.9 on 2026-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Marcar para mostrar en el carrusel principal', verbose_name='Es portada (Hero)'),
        ),
    ]
